### ISSUE TITLE
Need lwevt_unregister() api function 

### ISSUE THREAD

**Issue by Linjieqiang** [MaJerle/lwevt#3]

**Comment by Linjieqiang** [comment]
@MaJerle Any idea?

uint8_t lwevt_register(lwevt_fn evt_fn);
uint8_t lwevt_unregister(lwevt_fn evt_fn);

**Comment by MaJerle** [comment]
Can you justify the need for unregister function implementation? It doesn't seem natural for the system. If you need to it implement dynamic attach/detach from/to events, it is better you implement the glue logic above the LwEVT layer.

**Comment by Linjieqiang** [comment]
I implemented it myself.
